[runner]
magicEnabled = false
fastReruns = true

[theme]
primaryColor="#213ab3"
backgroundColor="#eaecd3"
secondaryBackgroundColor="#efd576"
textColor="#1a528e"
font = "Signika:https://fonts.googleapis.com/css2?family=Signika:wght@300..700&display=swap, sans-serif"
baseFontSize = 18

[client]
showSidebarNavigation = false